import FallHeader from '../../assets/Fall_Header.jpg';
import MoodyHeader from '../../assets/Moody_Header.jpg';
import TarotHeader from '../../assets/TarotHeader1.png';
import PastelHeader from '../../assets/Pastel_Header.jpg';
import JosephHeader from '../../assets/Joseph_Header.png';
import MoodyLogo from '../../assets/Logos/Large/MoodyLogo.png';
import FallLogo from '../../assets/Logos/Large/FallLogo.png';
import MainLogo from '../../assets/Logos/Large/MainLogo.png';
import PastelLogo from '../../assets/Logos/Large/PastelLogo.png';
import JosephLogo from '../../assets/Logos/Large/JosephLogo.png';

const themes = {
    // label: Fall Moods
    fall: {
        headerImage: FallHeader,
        logo: FallLogo,
        backgroundColor: '#141414',
        h2Color: '#00565E',
        h2TextShadow: '#121212',
        linkColor: '#00565e',
        linkShadow: '#d7d5ce',
        h3Color: '#D7D5CE',
        hrBorderColor: '#121212',
        borderLeftColor: '#DAA520',
        textColor: '#DAA520',
        userTextColor: '#D7D5CE',
        imgTextBgColor: '#00565e',
        universalImageBorder: '#00565e',
        avatarSettingsBorder: '#372B4F',
        panelColor: '#8C3D00',
        buttonColor: '#8C3D00',
        buttonSecondaryColor: '#d7d5ce',
        iconColor: '#D7D5CE',
        iconStyling: '#fafaf7',
        bodyColor: '#fcfbfb',
        trashCanColor: '#8c3d00',
        trashCanHoverColor: '#DAA520',
        disabled: '#DAA520',
        editableBackgroundColor: '#D7D5CE',
        editableBorderColor: '#00565E',
        editableTextColor: '#372B4F',
        fieldsInputBackgroundColor: '#D7D5CE',
        fieldsInputBorderColor: '#8C3D00',
        fieldsInputTextColor: '#561E1E'
    },
    // label: Scarlet Shadows - Christi's theme
    moody: {
        headerImage: MoodyHeader,
        logo: MoodyLogo,
        backgroundColor: '#F7F7F7',
        h2Color: '#7B2C2C',
        h2TextShadow: '#121212',
        linkColor: '#a89467',
        linkShadow: '#121212',
        h3Color: '#561E1E',
        hrBorderColor: '#121212',
        borderLeftColor: '#7b2c2c',
        textColor: '#7B2C2C',
        userTextColor: '#D7D5CE',
        imgTextBgColor: '#7b2c2c',
        universalImageBorder: '#7b2c2c',
        avatarSettingsBorder: '#7B2C2C',
        panelColor: '#121212',
        buttonColor: '#7B2C2C',
        buttonSecondaryColor: '#d0c9c0',
        iconColor: '#561E1E',
        iconStyling: '#d0c9c0',
        bodyColor: '#fcfbfb',
        trashCanColor: '#561e1e',
        trashCanHoverColor: '#7B2C2C',
        disabled: '#7B2C2C',
        editableBackgroundColor: '#D0C9C0',
        editableBorderColor: '#A89467',
        editableTextColor: '#561E1E',
        fieldsInputBackgroundColor: '#D0C9C0',
        fieldsInputBorderColor: '#A89467',
        fieldsInputTextColor: '#561E1E'
    },
    // label: Pastel Haunt - Andrea's theme
    pastel: {
        headerImage: PastelHeader,
        logo: PastelLogo,
        backgroundColor: '#468874',
        h2Color: '#AB8383',
        h2TextShadow: '#121212',
        linkColor: '#cdb167',
        linkShadow: '#121212',
        h3Color: '#CDB167',
        hrBorderColor: '#00565e',
        borderLeftColor: '#CDB167',
        textColor: '#C8C9C1',
        userTextColor: '#00565e',
        imgTextBgColor: '#00565e',
        universalImageBorder: '#cc8f8f',
        avatarSettingsBorder: '#cc8f8f',
        panelColor: '#C8C9C1',
        buttonColor: '#AB8383',
        buttonSecondaryColor: '#c8c9c1',
        iconColor: '#CD8167',
        iconStyling: '#00565e',
        bodyColor: '#00565e',
        trashCanColor: '#CDB167',
        trashCanHoverColor: '#C8C9C1',
        disabled: '#7B2C2C',
        navIconsContainerBackgroundColor: '#c8c9c1',
        editableBackgroundColor: '#C8C9C1',
        editableBorderColor: '#AB8383',
        editableTextColor: '#3A5256',
        fieldsInputBackgroundColor: '#C8C9C1',
        fieldsInputBorderColor: '#AB8383',
        fieldsInputTextColor: '#3A5256'
    },
    // label: Noble Charoite - Main theme
    main: {
        headerImage: TarotHeader,
        logo: MainLogo,
        backgroundColor: '#331834',
        h2Color: '#A89467',
        h2TextShadow: '#121212',
        linkColor: '#a89467',
        linkShadow: 'none',
        h3Color: '#A89467',
        hrBorderColor: '#A89467',
        borderLeftColor: '#A89467',
        textColor: '#FAFAF7',
        userTextColor: '#D7D5CE',
        imgTextBgColor: '#4f3052',
        universalImageBorder: '#A89467',
        avatarSettingsBorder: '#808080',
        panelColor: '#4F334A',
        buttonColor: '#A89467',
        buttonSecondaryColor: '#fafaf7',
        iconColor: '#A89467',
        iconStyling: '#fafaf7',
        bodyColor: '#A89467',
        trashCanColor: '#a89467',
        trashCanHoverColor: '#fafaf7',
        //    disabledColor: 'none',
        editableBackgroundColor: '#FAFAF7',
        editableBorderColor: '#A89467',
        editableTextColor: '#121212',
        fieldsInputBackgroundColor: '#4f3052',
        fieldsInputBorderColor: '#A89467',
        fieldsInputTextColor: '#FAFAF7'
    },
    // label: Joseph's Theme
    joseph: {
        headerImage: JosephHeader,
        logo: JosephLogo,
        backgroundColor: '#01497C',
        h2Color: '#fafaf7',
        h2TextShadow: '#121212',
        linkColor: '#fafaf7',
        linkShadow: '#121212',
        h3Color: '#fafaf7',
        hrBorderColor: '#80848D',
        borderLeftColor: '#80848D',
        textColor: '#c8c9c1',
        userTextColor: '#468FAF',
        imgTextBgColor: '#01497C',
        universalImageBorder: '#012A4A',
        avatarSettingsBorder: '#012A4A',
        panelColor: '#A9C3D9',
        buttonColor: '#012A4A',
        buttonSecondaryColor: '#468FAF',
        iconColor: '#A89467',
        iconStyling: '#80848D',
        bodyColor: '#c8c9c1',
        trashCanColor: '#80848D',
        trashCanHoverColor: '#c8c9c1',
        disabledColor: '#c8c9c1',
        navIconsContainerBackgroundColor: '#A9C3D9',
        editableBackgroundColor: '#A9D6E5',
        editableBorderColor: '#468FAF',
        editableTextColor: '#012A4A',
        fieldsInputBackgroundColor: '#A9D6E5',
        fieldsInputBorderColor: '#468FAF',
        fieldsInputTextColor: '#012A4A'
    }
};

export default themes;
